### ISSUE TITLE
Wayland: moves to 0, 0 no matter where you move it to when using abs cords

### ISSUE THREAD

**Issue by Zai-Kun** [enigo-rs/enigo#396]
**Describe the bug**
Pretty much as the title says. No matter what x,y cords you set, it just moves to 0, 0. However, relative seems to work.

**To Reproduce**
```rs
use enigo::{
    Enigo, Mouse, Settings,
    Coordinate::Abs
};

fn main() {
    let mut enigo = Enigo::new(&Settings::default()).unwrap();
    enigo.move_mouse(100 200, Abs).unwrap();
}
```

**Expected behavior**
Mouse cursor should move to the defined x,y cords.

**Environment (please complete the following information):**

- OS: linux, wayland, sway
- Rust rustc 1.84.0
- Library Version enigo 0.3.0

**Additional context**
None

https://github.com/user-attachments/assets/96da451a-c2f2-4dbe-b968-1e3590ec3d03

**Comment by pentamassiv** [comment]
Hi,
thank you for the report.

Could you please try again with the current main branch? I fixed a few Wayland issues recently. Also, can you tell me more about your environment? You say that you are using sway with Wayland. Which feature are you using to do that? `wayland`, `libei` or just the default (then you are using XWayland)? Does everything else work (e.g left click with the mouse)?

**Comment by Zai-Kun** [comment]
I cloned the main repo using `git clone https://github.com/enigo-rs/enigo`, and specified the cloned dir in cargo.toml. Here is what it looks like:
```toml
[package]
name = "lol"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = { path = "/tmp/enigo", features = ["wayland"] }
```
That did not solve the issue but introduced another issue. A weird one at that. It doesn't take effect until i switch my workspace. Please see the attached video:

https://github.com/user-attachments/assets/05419f49-c3cf-4111-848a-ea8cac25538f

After tinkering around with the source code I bit, I discovered that changing the arguments in the
```rs
                vp.motion_absolute(
                    time,
                    x,
                    y,
                    u32::MAX, // TODO: Check what would be the correct value here
                    u32::MAX, // TODO: Check what would be the correct value here
                );
```
function from u32:MAX to my width and height of the screen somehow fished the first issue. 

https://github.com/user-attachments/assets/7b618188-eb7d-4f71-9515-facad622363d

About the question earlier, mouse button clicks seem to work just fine.

**Comment by pentamassiv** [comment]
Nice find, now we need to find out how to get the correct screen dimensions dynamically

Regarding your videos, I don't understand what I am seeing in them. Maybe it is because I never used sway, but I can't tell when you change workspaces and if it is intentional or not. I also don't get what enigo is supposed to do. Is it executing the same code as before (i.e it is just supposed to move the mouse)?

**Comment by Zai-Kun** [comment]
I'm sorry for not being clear. What I wanted to show was, that no matter how long I keep the program running nothing happens, not until I switch my workspace. The code used is the same as before:
```rs
use enigo::{
    Enigo, Mouse, Settings,
    Coordinate::Abs
};

fn main() {
    let mut enigo = Enigo::new(&Settings::default()).unwrap();
    enigo.move_mouse(500, 500, Abs).unwrap();
}
```

Focus on my mouse pointer; it suddenly moves when I switch a workspace, and *then* the program exits. Now, another weird part about it is, that it only happens when I move to a workspace with a window, and not with an empty one. 

https://github.com/user-attachments/assets/adcddc00-f9fc-4f30-9898-f52fb73a87b6

Those numbers at the top indicate my workspaces. 3rd workspace is where I was running the program 2nd workspace is where I had another terminal open. As you can see, when I switch to an empty workspace, workspace 4 for example, nothing happens. But when I do the same with a workspace with a window on it, my cursor moves and the program exists. I hope that explained it.

**Comment by pentamassiv** [comment]
No problem, I understand it now.

I have a suspicion why the program does not terminate unless the workspace is switched. Could you please try out the fix from https://github.com/enigo-rs/enigo/pull/398?

You should be able to just change your Cargo.toml to include

```toml
enigo = { git = "https://github.com/pentamassiv/enigo.git", branch = "wayland_sway_roundtrip" }
```

I haven't tested it myself yet, but it should fix the issue of the program not terminating. It might still only successfully simulate the mouse move after you change workspaces. Please let me know what happens :-)

**Comment by Zai-Kun** [comment]
Unfortunately, that did not seem to fix the issue :(

**Comment by pentamassiv** [comment]
What happened? Is the program still not terminating before switching workspaces?

Then it must be waiting for a previous Wayland message. That makes sense, as the changes I recently merged were touching the initialization of the connection. Could you please change your Cargo.toml file to this:

```toml
[package]
name = "lol"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = { git = "https://github.com/pentamassiv/enigo.git", branch = "wayland_sway_roundtrip", features = ["wayland"] }
env_logger = "0.11"
```

and please change your code to this:

```Rust
use enigo::{
    Enigo, Mouse, Settings,
    Coordinate::Abs
};

fn main() {
    env_logger::try_init().ok();
    let mut enigo = Enigo::new(&Settings::default()).unwrap();
    enigo.move_mouse(100 200, Abs).unwrap();
}
```

Please start the program by running `WAYLAND_DEBUG=1 RUST_LOG=debug cargo run` (or adapt your script to add the environment flags). This will print the sent and received Wayland messages (it's a long output, so you probably want to pipe it to a file). Please paste the output of a successful run (you switched workspaces for it to finish) and paste the output of the program running until it is supposed to simulate the mouse move (press CTRL+C before switching the workspace). This should help us determine why it hangs.

**Comment by Zai-Kun** [comment]
Yes, the problem persists. 
Here is the successful run output:

[successful_run.txt](https://github.com/user-attachments/files/19006235/successful_run.txt)

Here is the interrupted one:

[interrupted_run.txt](https://github.com/user-attachments/files/19006268/interrupted_run.txt)

**Comment by Zai-Kun** [comment]
Perfect! Goodluck with your exams :)

**Comment by pentamassiv** [comment]
Thank you, the exams went ok.

I created the PR https://github.com/enigo-rs/enigo/pull/402 to address this issue. I have not tested it yet, so it might not work. I'll test it within the next couple of days. I just have to get the right cable to connect a Raspberry Pi to my screen and then put a DE on it that supports the needed Wayland protocols

**Comment by Zai-Kun** [comment]
> Thank you, the exams went ok.
> 
> I created the PR [#402](https://github.com/enigo-rs/enigo/pull/402) to address this issue. I have not tested it yet, so it might not work. I'll test it within the next couple of days. I just have to get the right cable to connect a Raspberry Pi to my screen and then put a DE on it that supports the needed Wayland protocols

Great! I will test the PR and let you know if it works.

**Comment by Zai-Kun** [comment]
That PR solved the first issue! Now, just that new weird problem persists.

**Comment by pentamassiv** [comment]
That one should get solved with this PR https://github.com/enigo-rs/enigo/pull/403 :-)

I finally was able to install labwc and sway in a VM running minimal Arch Linux. I only tested the keyboard example, but at least that one worked

**Comment by Zai-Kun** [comment]
> That one should get solved with this PR [#403](https://github.com/enigo-rs/enigo/pull/403) :-)
> 
> I finally was able to install labwc and sway in a VM running minimal Arch Linux. I only tested the keyboard example, but at least that one worked

Wonderful:) should I test the PR right now?

**Comment by pentamassiv** [comment]
Yes, it works on Gnome too. It uses the [libei protocol](https://web.archive.org/web/20240201000000*/https://libinput.pages.freedesktop.org/libei/api/index.html) there and also on KDE (might be outdated, but the current website is offline due to the freedesktop migration). It's another experimental feature in enigo, so you have to opt-in.

Unfortunately there are three implementations for Linux (X11, Wayland and libei). They don't cover 100% but most compositors should work with them

**Comment by pentamassiv** [comment]
Feel free to test it if you'd like to. I'll test it tomorrow as well

**Comment by Zai-Kun** [comment]
> Yes, it works on Gnome too. It uses the [libei protocol](https://web.archive.org/web/20240201000000*/https://libinput.pages.freedesktop.org/libei/api/index.html) there and also on KDE (might be outdated, but the current website is offline due to the freedesktop migration). It's another experimental feature in enigo, so you have to opt-in.
> 
> Unfortunately there are three implementations for Linux (X11, Wayland and libei). They don't cover 100% but most compositors should work with them

Ahh, I see, that's awesome!

**Comment by Zai-Kun** [comment]
> Feel free to test it if you'd like to. I'll test it tomorrow as well

Great, the PR fixed that issue! Now, everything seems to work perfectly :-)
